config/routes.rb
Rails.application.routes.draw do


  resources :items
  get "items/:id" => "items#show"
  
  scope module: :admin do
    devise_for :admin, controllers: {
      sessions: 'admin/sessions',
      passwords: 'admin/passwords',
      registrations: 'admin/registrations'
    }
    end
    
    namespace :admin do
      
    devise_for :admin
    resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :genres
    post 'admin/genres/:id/edit' => 'admin_genres#edit'
    resources :customers
  end
  
  
  root to: 'homes#top'
  resource :customers, only: [:index, :show, :edit, :update]
  get  "/about" => "homes#about"
  get "/customers/my_page" => "customers#show"
  
  devise_for :customers
  
  get 'customers/unsubscribe/' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
  patch ':customers/withdraw/' => 'customers#withdraw', as: 'withdraw_customer'
  
  
  resources :cart_items do
   delete 'destroy_all'
 end
 
  post '/cart_item' => 'cart_items#index'
  post '/cart_items/:id' => 'cart_items#update'
  
  post 'orders/confirm' => 'orders#confirm'
  resources :orders


  
  resources :order_details
  

  resources :addresses
  
 end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :addresses
  
  enum is_active: {
    
    "有効":true, "退会":false
    
  }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
      @customers = Customer.all
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
   @customer = Customer.find(params[:id])
   @customer.update(customer_params)
   redirect_to admin_customer_path(@customer)
  end
  
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :id, :email)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
 def index
  @cutomers = Customer.all

 end

  
  def show
   @customer = current_customer
  end  

  def edit
   @customer = current_customer 
  end

  def update
   @customer = current_customer
   @customer.update(customer_params)
   redirect_to customers_my_page_path
  end

  def unsubscribe
   @customer = current_customer
  end

  def withdraw
    @customer = current_customer
    @customer.update(is_deleted: false)
    reset_session
    redirect_to root_path
  end
  
  def reject_inactive_user
    @customer = current_customer
    if @customer
      if @customer.valid_password?(params[:email][:encrypted_password]) && !@customer.is_valid
        redirect_to new_customer_session_path
      end
    end
  end

  
 private
 def customer_params
    params.require(:customer).permit(:email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
 end
 
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<h2>会員情報編集</h2>

<%= form_with model:@customer, url: customers_path, local:true do |f| %>
  

　<div class="field">
    名前 (姓）<%= f.text_field :last_name, autofocus: true %>
    (名）<%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    (セイ）<%= f.text_field :last_name_kana, autofoucus: true %>
    （メイ）<%= f.text_field :first_name_kana, autofoucus: true %>
  </div>

  <div class="field">
    メールアドレス
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    郵便番号（ハイフンなし）
    <%= f.text_field :postal_code %>
  </div>

  <div class="field">
    住所
    <%= f.text_field :address %>
  </div>

  <div class="field">
    電話番号
    <%= f.text_field :telephone_number %>
  </div>

  <div class="field">
    パスワード（６文字以上）
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %>
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    パスワード（確認用）
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "変更を保存する" %> 
  </div>
<% end %>

app/views/customers/show.html.erb
<h1>マイページ</h1>

<h2>登録情報</h2>　<%= link_to "編集する", edit_customers_path %>

<table>
  <tr>
  <th>氏名：</th><td><%= @customer.last_name %><%= @customer.first_name %></td>
  </tr>
  
  <tr>
    <th>カナ：</th><td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
  </tr>
  
  <tr>
    <th>郵便番号：</th><td><%= @customer.postal_code %></td>
  </tr>
  
  <tr>
    <th>住所：</th><td><%= @customer.address %></td>
  </tr>
  
  <tr>
    <th>電話番号：</th><td><%= @customer.telephone_number %></td>
  </tr>
  
  <tr>
    <th>メールアドレス：</th><td><%= @customer.email %></td>
  </tr>
  </table>
  
  
 
  

app/views/customers/unsubscribe.html.erb
<div>
  <h2>本当に退会しますか？</h2>
  <div>
    <p>退会する場合は、『退会する』をクリックしてください。</p>
  </div>
  <div>
    <%= link_to '退会しない', root_path %>
    <%= link_to "退会する", withdraw_customer_path(@customer), method: :patch %>
  </div>
</div>

app/views/customers/update.html.erb
<h1>Customers#update</h1>
<p>Find me in app/views/customers/update.html.erb</p>

app/views/customers/withdraw.html.erb
<h1>Customers#withdraw</h1>
<p>Find me in app/views/customers/withdraw.html.erb</p>