config/routes.rb
Rails.application.routes.draw do


  resources :items
  get "items/:id" => "items#show"
  
  scope module: :admin do
    devise_for :admin, controllers: {
      sessions: 'admin/sessions',
      passwords: 'admin/passwords',
      registrations: 'admin/registrations'
    }
    end
    
    namespace :admin do
      
    devise_for :admin
    resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :genres
    post 'admin/genres/:id/edit' => 'admin_genres#edit'
    resources :customers
  end
  
  
  root to: 'homes#top'
  resource :customers, only: [:index, :show, :edit, :update]
  get  "/about" => "homes#about"
  get "/customers/my_page" => "customers#show"
  
  devise_for :customers
  
  get 'customers/unsubscribe/' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
  patch ':customers/withdraw/' => 'customers#withdraw', as: 'withdraw_customer'
  
  
  resources :cart_items do
   delete 'destroy_all'
 end
 
  post '/cart_item' => 'cart_items#index'
  post '/cart_items/:id' => 'cart_items#update'
  
  post 'orders/confirm' => 'orders#confirm'
  resources :orders


  
  resources :order_details
  

  resources :addresses
  
 end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :customer
 belongs_to :item
 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :addresses
  
  enum is_active: {
    
    "有効":true, "退会":false
    
  }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  
  enum is_active: {
    
    "販売中":true, "販売停止中":false
    
  }
  
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: {クレジット:1, 現金:2}
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
 def index
  @addresses = current_customer.addresses
  @address = Address.new
 end
 
 def create
    @address = current_customer.addresses.new(address_params)
    @address.save
    redirect_to addresses_path
 end
 
 def edit
   @address = Address.find(params[:id])
 end
 
 def update
  @address = Address.find(params[:id])
  @address.update(address_params)
  redirect_to addresses_path
 end
 
 def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path
 end
 
 private
 def address_params
    params.require(:address).permit(:name, :postal_cade, :address)
 end
 
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @tax = 1.1
    @cart_items = current_customer.cart_items
  end
  
  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_item_path(@cart_item)
  end   
  
  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    # @genre = Genre.new(genre_params)
    @cart_item.save
    redirect_to cart_items_path
  end
  

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end
  
  def destroy_all
    @cart_items = CartItem.all
    @cart_items.destroy_all
    redirect_to cart_items_path
  end
  
private
  def cart_item_params
    params.require(:cart_item).permit(:amount, :customer_id, :item_id)
  end

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end
 
      

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
 def index
  @cutomers = Customer.all

 end

  
  def show
   @customer = current_customer
  end  

  def edit
   @customer = current_customer 
  end

  def update
   @customer = current_customer
   @customer.update(customer_params)
   redirect_to customers_my_page_path
  end

  def unsubscribe
   @customer = current_customer
  end

  def withdraw
    @customer = current_customer
    @customer.update(is_deleted: false)
    reset_session
    redirect_to root_path
  end
  
  def reject_inactive_user
    @customer = current_customer
    if @customer
      if @customer.valid_password?(params[:email][:encrypted_password]) && !@customer.is_valid
        redirect_to new_customer_session_path
      end
    end
  end

  
 private
 def customer_params
    params.require(:customer).permit(:email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
 end
 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 def top
  @tax = 1.1
  @items = Item.all
 end 
 def about
 end
 
 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @tax = 1.1
    @items = Item.all
  end

  def new
  end

  def show
    @tax = 1.1
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  def edit
  end
  
  
  private
 def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
 end
 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def new
    @order = Order.new
    @customer = current_customer
  end
  
  def confirm
      @tax = 1.1
      @order = Order.new
      @order.payment_method = params[:order][:payment_method]
      @cart_items = current_customer.cart_items

 
    if params[:order][:address_option] == "1"
    @addresses = current_customer.addresses.find(params[:order][:addresses])
    @order.address = @addresses.address
    @order.name = @addresses.name
    @order.postal_code = @addresses.postal_cade
   
    
    
    elsif params[:order][:address_option] == "2"
      @order.postal_code = params[:order][:postal_code]  
      @order.address = params[:order][:address]  
      @order.name = params[:order][:name]
    
    elsif params[:order][:address_option] == "0"
      
    @order = Order.new(order_comfirm_params) 
    @order.total_payment = 100 #あとで計算する
    @order.shipping_cost = 800
    @order.address = current_customer.address
    @order.postal_code = current_customer.postal_code
    @order.name = current_customer.last_name + " " + current_customer.first_name
    @order.customer_id = current_customer.id
    @order.status = 0
    
    end 
        
      
  end  
  
  def create
    @order = Order.new
    @order.save
    redirect_to order_confirm_path(@order)
  end
  

  def show
  end
  
  private
 def order_params
    params.require(:order).permit(:postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method)
 end
 
 def order_comfirm_params
    params.permit(:postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method)
 end
 
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/cart_items/index.html.erb
<h1>ショッピングカート</h1>

<%= button_to "カートを空にする",  cart_item_destroy_all_path(@cart_items), method: :delete %>

<table>
 <thead>
  <tr>
   <th>商品名</th>
   <th>単価（税込）</th>
   <th>数量</th>
   <th>小計</th>
  </tr>
 </thead>
<tbody>
   <% @sum = 0 %>
   <% @cart_items.each do |cart_item| %>
  <tr>
   <td><%= cart_item.item.name %> </td>
   <td><%= (cart_item.item.price * @tax.round(1)).ceil %></td>
   <td><%= cart_item.amount %></td>
   <td><%= ((cart_item.item.price * @tax.round(1)).ceil*cart_item.amount).to_i %></td>
   <td><%= link_to "削除", cart_item_path(cart_item), method: :delete,
            data: {confirm: "本当にいいですか？"}, class: "btn btn-danger" %></td>
  <% @sum += ((cart_item.item.price * @tax.round(1)).ceil*cart_item.amount).to_i %>
  <% end %>
  </tr>
</tbody>
</table>
<%= link_to "買い物を続ける", items_path %> 合計金額：<%= @sum %><br>

<%= link_to "情報入力に進む",  new_order_path %>

app/views/orders/confirm.html.erb
<h1>注文確認画面</h1>
<table>
    <tr>
        <th>商品名</th>
        <th>単価（税込）</th>
        <th>数量</th>
        <th>小計</th>
    </tr>
    <tr>
        <% @sum = 0 %>
        <% @cart_items.each do |cart_item| %>
        <td><%= cart_item.item.name %></td>
        <td><%= cart_item.item.price %></td>
        <td><%= cart_item.amount %></td>
        <td><%= ((cart_item.item.price * @tax.round(1)).ceil*cart_item.amount).to_i %></td>
        <% @sum %>
      <% end %>
</table>

<br>

<h2>支払い方法</h2><%= @order.payment_method %>

<h2>お届け先</h2>〒<%= @order.postal_code %><%= @order.address %><br>
<%= @order.name %>

<table>
    <tr>
        <th>送料</th> <td><%= @order.shipping_cost %></td>
    </tr>
    <tr>
        <th>商品合計</th> <td><%= @order.total_payment %></td>
    </tr>
    <tr>
        <th>請求金額</th> <td></td>
    </tr>
</table>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>注文情報入力</h1>
<%= form_with model: @order, url: orders_confirm_path, local:true do |f| %>
<h2>支払い方法</h2>
<%= f.radio_button :payment_method, "クレジット" %>
<%= f.label :payment_method, "クレジット", {value: :credit, style: "display: inline-block;"} %>
<%= f.radio_button :payment_method, "現金" %>
<%= f.label :payment_method, "現金", {value: :cash, style: "display: inline-block;"} %>

<h2>お届け先</h2>
<%= f.radio_button :address_option, 0 %>
<%= f.label :address, "ご自身の住所" %>
〒<%= @customer.postal_code %> <%= @customer.address %> <br>
<%= @customer.last_name %><%= @customer.first_name %>

<br>  
<%= f.radio_button :address_option, 1 %>  
<%= f.label :addresses, "登録済住所から選択" %> 
<%= f.collection_select :addresses , current_customer.addresses, :id, :address, :include_blank => "選択してください" %>

<br>
<%= f.radio_button :address_option, 2 %>
<%= f.label :address, "新しいお届け先" %>
<p>郵便番号<%= f.text_field :postal_code, autofocus: true %></p>
<p>住所<%= f.text_field :address, autofocus: true %></p>
<p>宛名<%= f.text_field :name, autofocus: true %></p>
<%= f.submit "確認画面に進む" %> 


<% end %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>