config/routes.rb
Rails.application.routes.draw do


  resources :items
  get "items/:id" => "items#show"
  
  scope module: :admin do
    devise_for :admin, controllers: {
      sessions: 'admin/sessions',
      passwords: 'admin/passwords',
      registrations: 'admin/registrations'
    }
    end
    
    namespace :admin do
      
    devise_for :admin
    resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :genres
    post 'admin/genres/:id/edit' => 'admin_genres#edit'
    resources :customers
  end
  
  
  root to: 'homes#top'
  resource :customers, only: [:index, :show, :edit, :update]
  get  "/about" => "homes#about"
  get "/customers/my_page" => "customers#show"
  
  devise_for :customers
  
  get 'customers/unsubscribe/' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
  patch ':customers/withdraw/' => 'customers#withdraw', as: 'withdraw_customer'
  
  
  resources :cart_items do
   delete 'destroy_all'
 end
 
  post '/cart_item' => 'cart_items#index'
  post '/cart_items/:id' => 'cart_items#update'
  
  post 'orders/confirm' => 'orders#confirm'
  resources :orders


  
  resources :order_details
  

  resources :addresses
  
 end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  
  enum is_active: {
    
    "販売中":true, "販売停止中":false
    
  }
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
  def new
    @items = Item.all
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    # @genre = Genre.new(genre_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  def destroy
  end
  
private
 def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
 end
 
end

 

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @tax = 1.1
    @items = Item.all
  end

  def new
  end

  def show
    @tax = 1.1
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  def edit
  end
  
  
  private
 def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
 end
 
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<% @items.each do |item| %>
<%= link_to item_path(item) do %>
<%= attachment_image_tag item, :image, :fill, 300, 200 %>
<% end %>
<%= item.name %>
<%= (item.price * @tax.round(1)).ceil %>
<% end %>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1>商品詳細ページ</h1>

<%= form_with model: @cart_item, url: cart_items_path, local:true do |f| %>
<%= f.hidden_field :item_id, :value => @item.id %>
 <p><%= attachment_image_tag @item, :image, :fill, 300, 200  %></p>
 <h2><%= @item.name %></h2>
 <p><%= @item.introduction %></p>
 <p>¥<%= (@item.price * @tax.round(1)).ceil %>(税込）</p>
 <p><%= f.select :amount, ['1', '2', '3'], {include_blank: '個数選択'}, 
class: 'amount' %></p>
 <%= f.submit 'カートに追加する' %>
 <% end %>
 
 